
stages:          # List of stages for jobs, and their order of execution
  - test

net462-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - "dotnet test --framework net462 -v:normal -l \"console;verbosity=detailed\" crypto\\test\\BouncyCastle.Crypto.Tests.csproj"

net60-job:
  stage: test
  script:
    - "dotnet test --framework net6.0 -v:normal -l \"console;verbosity=detailed\" crypto\\test\\BouncyCastle.Crypto.Tests.csproj"

netcoreapp311-job:
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - "dotnet test --framework netcoreapp3 -v:normal -l \"console;verbosity=detailed\" crypto\\test\\BouncyCastle.Crypto.Tests.csproj"
