configuration: Release
image: Visual Studio 2017 RC

environment:
  SignClientSecret:
    secure: S26+NphAhj/vo5ZdHd/N/4toty3ztdNGmuNdvAB57W1oIVQEHVKqAVuhTD8B9ATy

install:  
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/NuGet.exe
  - cmd: nuget install gitlink -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion
  - cmd: nuget install SignClient -Version 0.5.0-beta4 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre

assembly_info:
  patch: false
        
build_script:
  - cmd: dotnet restore BouncyCastle.sln
  - cmd: dotnet pack BouncyCastle.sln -c Release /p:PackageId="Portable.BouncyCastle" /p:PackageOutputPath="%APPVEYOR_BUILD_FOLDER%"
  
after_build:
  - cmd: '.\packages\gitlink\lib\net45\GitLink.exe . -f BouncyCastle.sln -u https://github.com/onovotny/bc-csharp -c Release -s %APPVEYOR_REPO_COMMIT% -errorsaswarnings'    
  - ps: '.\scripts\Sign-Package.ps1'  
  - ps: 'cmd /c "appveyor PushArtifact Portable.BouncyCastle.*.nupkg";if($lastexitcode -ne 0){$lastexitcode = 0}'