configuration: Release
image: Visual Studio 2017 RC

environment:
  SignClientSecret:
    secure: S26+NphAhj/vo5ZdHd/N/4toty3ztdNGmuNdvAB57W1oIVQEHVKqAVuhTD8B9ATy

install:  
  - cmd: nuget install SignClient -Version 0.5.0-beta4 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre

assembly_info:
  patch: false
        
build_script:
  - cmd: msbuild /t:restore BouncyCastle.sln
  - cmd: msbuild /t:build BouncyCastle.sln 
  - cmd: msbuild /t:pack crypto\src\crypto.csproj /p:PackageId="Portable.BouncyCastle" /p:PackageOutputPath="%APPVEYOR_BUILD_FOLDER%"
  
after_build:  
  - ps: '.\scripts\Sign-Package.ps1'  
  - ps: 'cmd /c "appveyor PushArtifact *.nupkg";if($lastexitcode -ne 0){$lastexitcode = 0}'