configuration: Release
image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

environment:
  SignClientSecret:
    secure: mn/Un/p3QvEv5TKe2f1NGmppCIMk0jslsTaw8P4+pBQ=
  SignClientUser:
    secure: q9qZlA/a+Z3wQbRlcjWok/PkfODgpKNECOBCzu2yIGE=

install:  
  - cmd: nuget install SignClient -Version 0.9.1 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion 

build_script:  
  - cmd: msbuild /restore /t:build BouncyCastle.sln /p:Configuration=Release
  - cmd: msbuild /t:pack crypto\src\crypto.csproj /p:PackageId="Portable.BouncyCastle" /p:PackageOutputPath="%APPVEYOR_BUILD_FOLDER%"  
  
after_build:  
  - ps: '.\scripts\Sign-Package.ps1'  
  - cmd: dotnet test crypto\test\crypto.test.csproj --no-build

artifacts:
  - path: '*.nupkg'

test: off
